---
title: "Meghana H3K4me3 Maintenance - 01 H3K4me3_dynamics"
output: html_notebook
---

## Settings
```{r}
clustered_chip_groups <- TRUE

chip_clustering <- list("Kept" = "Y_Y_Y_Y", "Recovered"="Y_Y_N_Y", "Lost@ZGA"="Y_Y_Y_N", "Lost@Pre-ZGA"="Y_Y_N_N", "Lost@Sperm"="Y_N_N_N", "GainedEarly"="N_N_Y_Y", "GainedLate"="N_N_N_Y", "Absent"="N_N_N_N")
cols_clustered = setNames(c("#6ca239","#6bc7ab","#f2c237","#e17e39","#b73a2f","#5f91c1","#3b4ca8","grey"), names(chip_clustering))

#chip_clustering <- list(Kept = "Y_Y_Y_Y", Recovered="Y_Y_N_Y", Lost=c("Y_Y_Y_N", "Y_Y_N_N", "Y_N_N_N"), Gained=c("N_N_Y_Y", "N_N_N_Y"), Absent="N_N_N_N")
#cols_clustered = setNames(c("#6ca239","#f2c237","#b73a2f", "#3b4ca8", "grey"), names(chip_clustering))

#chip_clustering <- list(N_Y_ = "N_Y_Y_Y", "N_Y_Y_N", "N_Y_N_Y", "N_Y_N_N"), Y_Y_ = c("Y_Y_Y_Y", "Y_Y_Y_N", "Y_Y_N_Y", "Y_Y_N_N"), Y_N_ = c("Y_N_Y_Y", "Y_N_Y_N", "Y_N_N_Y", "Y_N_N_N"), Absent="N_N_N_N"))

load("h3k4me3_data_sperm_Oikawa.RData")
```

```{r}
#Definition of dynamic groups
chip_names_complete <- c("Y_Y_Y_Y", "Y_Y_Y_N", "Y_Y_N_Y", "Y_Y_N_N", "Y_N_Y_Y", "Y_N_Y_N", "Y_N_N_Y", "Y_N_N_N", "N_Y_Y_Y", "N_Y_Y_N", "N_Y_N_Y", "N_Y_N_N", "N_N_Y_Y", "N_N_Y_N", "N_N_N_Y", "N_N_N_N")
genes <- allgenes$gene_id
N_Y_Y_Y = genes[!chip_dfs[["Spermatid"]]$peak & chip_dfs[["Sperm"]]$peak & chip_dfs[["Pre-ZGA"]]$peak & chip_dfs[["ZGA"]]$peak] #0-1-1-1
N_Y_Y_N = genes[!chip_dfs[["Spermatid"]]$peak & chip_dfs[["Sperm"]]$peak & chip_dfs[["Pre-ZGA"]]$peak & !chip_dfs[["ZGA"]]$peak] #0-1-1-0
N_Y_N_Y = genes[!chip_dfs[["Spermatid"]]$peak & chip_dfs[["Sperm"]]$peak & !chip_dfs[["Pre-ZGA"]]$peak & chip_dfs[["ZGA"]]$peak] #0-1-0-1
N_Y_N_N = genes[!chip_dfs[["Spermatid"]]$peak & chip_dfs[["Sperm"]]$peak & !chip_dfs[["Pre-ZGA"]]$peak & !chip_dfs[["ZGA"]]$peak] #0-1-0-0
N_N_Y_Y = genes[!chip_dfs[["Spermatid"]]$peak & !chip_dfs[["Sperm"]]$peak & chip_dfs[["Pre-ZGA"]]$peak & chip_dfs[["ZGA"]]$peak] #0-0-1-1
N_N_Y_N = genes[!chip_dfs[["Spermatid"]]$peak & !chip_dfs[["Sperm"]]$peak & chip_dfs[["Pre-ZGA"]]$peak & !chip_dfs[["ZGA"]]$peak] #0-0-1-0
N_N_N_Y = genes[!chip_dfs[["Spermatid"]]$peak & !chip_dfs[["Sperm"]]$peak & !chip_dfs[["Pre-ZGA"]]$peak & chip_dfs[["ZGA"]]$peak] #0-0-0-1
N_N_N_N = genes[!chip_dfs[["Spermatid"]]$peak & !chip_dfs[["Sperm"]]$peak & !chip_dfs[["Pre-ZGA"]]$peak & !chip_dfs[["ZGA"]]$peak] #0-0-0-0

Y_Y_Y_Y = genes[chip_dfs[["Spermatid"]]$peak & chip_dfs[["Sperm"]]$peak & chip_dfs[["Pre-ZGA"]]$peak & chip_dfs[["ZGA"]]$peak] #1-1-1-1
Y_Y_Y_N = genes[chip_dfs[["Spermatid"]]$peak & chip_dfs[["Sperm"]]$peak & chip_dfs[["Pre-ZGA"]]$peak & !chip_dfs[["ZGA"]]$peak] #1-1-1-0
Y_Y_N_Y = genes[chip_dfs[["Spermatid"]]$peak & chip_dfs[["Sperm"]]$peak & !chip_dfs[["Pre-ZGA"]]$peak & chip_dfs[["ZGA"]]$peak] #1-1-0-1
Y_Y_N_N = genes[chip_dfs[["Spermatid"]]$peak & chip_dfs[["Sperm"]]$peak & !chip_dfs[["Pre-ZGA"]]$peak & !chip_dfs[["ZGA"]]$peak] #1-1-0-0
Y_N_Y_Y = genes[chip_dfs[["Spermatid"]]$peak & !chip_dfs[["Sperm"]]$peak & chip_dfs[["Pre-ZGA"]]$peak & chip_dfs[["ZGA"]]$peak] #1-0-1-1
Y_N_Y_N = genes[chip_dfs[["Spermatid"]]$peak & !chip_dfs[["Sperm"]]$peak & chip_dfs[["Pre-ZGA"]]$peak & !chip_dfs[["ZGA"]]$peak] #1-0-1-0
Y_N_N_Y = genes[chip_dfs[["Spermatid"]]$peak & !chip_dfs[["Sperm"]]$peak & !chip_dfs[["Pre-ZGA"]]$peak & chip_dfs[["ZGA"]]$peak] #1-0-0-1
Y_N_N_N = genes[chip_dfs[["Spermatid"]]$peak & !chip_dfs[["Sperm"]]$peak & !chip_dfs[["Pre-ZGA"]]$peak & !chip_dfs[["ZGA"]]$peak] #1-0-0-0

if(clustered_chip_groups){
  chip_dyns <- lapply(chip_clustering, function(cluster){unlist(sapply(cluster, function(dyn_name){get(dyn_name)}), use.names = FALSE)})
  cols_chipdyns <- cols_clustered
} else {
  cols_chipdyns <- setNames(c("#ece0d3","#a6afb7","#937c65","#625c5a","#be8162","#713725","#b73a2f","#e17e39","#f2c237","#6ca239","#36753d","#3b4ca8","#5f91c1","#6bc7ab","#d0589f","#8d55ae"), chip_names_complete)
  chip_dyns <- setNames(list(Y_Y_Y_Y, Y_Y_Y_N, Y_Y_N_Y, Y_Y_N_N, Y_N_Y_Y, Y_N_Y_N, Y_N_N_Y, Y_N_N_N,
N_Y_Y_Y, N_Y_Y_N, N_Y_N_Y, N_Y_N_N, N_N_Y_Y, N_N_Y_N, N_N_N_Y, N_N_N_N), chip_names_complete)
}
chip_dyns_complete <- setNames(list(Y_Y_Y_Y, Y_Y_Y_N, Y_Y_N_Y, Y_Y_N_N, Y_N_Y_Y, Y_N_Y_N, Y_N_N_Y, Y_N_N_N,
N_Y_Y_Y, N_Y_Y_N, N_Y_N_Y, N_Y_N_N, N_N_Y_Y, N_N_Y_N, N_N_N_Y, N_N_N_N), chip_names_complete)
chip_dyns_sizes = unlist(lapply(chip_dyns, function(x) length(x)))
```

## Save data
```{r}
if(clustered_chip_groups){
  save(chip_dyns, cols_chipdyns, file="chip_data_clustered.RData")
} else {
  save(chip_dyns, cols_chipdyns, file="chip_data.RData")
}
```

## Plot legend
```{r fig.height=6, fig.width=3}
remove_NNNN <- TRUE

groups <- names(chip_dyns)
if(remove_NNNN){groups <- groups[!groups %in% c("N_N_N_N", "Absent")]}

plot(NULL ,xaxt='n',yaxt='n',bty='n',ylab='',xlab='', xlim=0:1, ylim=0:1)
legend("topright", title="H3K4me3 dynamics",
groups, fill=cols_chipdyns[groups], horiz=FALSE)
```

##Venn diagram of H3K4me3 dynamics
```{r}
library(eulerr)
if(clustered_chip_groups){
  euler_cols <- setNames(rep("#d3d3d3", 16), chip_names_complete)
  for(i in 1:length(chip_clustering)){
    cluster <- chip_clustering[[i]]
    for(dynamic in cluster){
      euler_cols[dynamic]=cols_chipdyns[names(chip_clustering)[i]]
    }
  }
} else {
  euler_cols <- cols_chipdyns
}
plot(euler(c("Spermatid"=length(Y_N_N_N), "Sperm"=length(N_Y_N_N), "Pre-ZGA"=length(N_N_Y_N), "ZGA"=length(N_N_N_Y),
           "Spermatid&Sperm"=length(Y_Y_N_N), "Spermatid&Pre-ZGA"=length(Y_N_Y_N), "Spermatid&ZGA"=length(Y_N_N_Y),
           "Sperm&Pre-ZGA"=length(N_Y_Y_N), "Sperm&ZGA"=length(N_Y_N_Y), "Pre-ZGA&ZGA"=length(N_N_Y_Y),
      "Spermatid&Sperm&Pre-ZGA"=length(Y_Y_Y_N), "Spermatid&Sperm&ZGA"=length(Y_Y_N_Y), "Spermatid&Pre-ZGA&ZGA"=length(Y_N_Y_Y),
      "Sperm&Pre-ZGA&ZGA"=length(N_Y_Y_Y), "Spermatid&Sperm&Pre-ZGA&ZGA"=length(Y_Y_Y_Y))),
     quantities = TRUE,  fills=euler_cols[c("Y_N_N_N", "N_Y_N_N", "N_N_Y_N", "N_N_N_Y", "Y_Y_N_N", "Y_N_Y_N", "Y_N_N_Y", "N_Y_Y_N", "N_Y_N_Y", "N_N_Y_Y", "Y_Y_Y_N", "Y_Y_N_Y", "Y_N_Y_Y", "N_Y_Y_Y", "Y_Y_Y_Y")])

plot(venn(c("Spermatid"=length(Y_N_N_N), "Sperm"=length(N_Y_N_N), "Pre-ZGA"=length(N_N_Y_N), "ZGA"=length(N_N_N_Y),
           "Spermatid&Sperm"=length(Y_Y_N_N), "Spermatid&Pre-ZGA"=length(Y_N_Y_N), "Spermatid&ZGA"=length(Y_N_N_Y),
           "Sperm&Pre-ZGA"=length(N_Y_Y_N), "Sperm&ZGA"=length(N_Y_N_Y), "Pre-ZGA&ZGA"=length(N_N_Y_Y),
      "Spermatid&Sperm&Pre-ZGA"=length(Y_Y_Y_N), "Spermatid&Sperm&ZGA"=length(Y_Y_N_Y), "Spermatid&Pre-ZGA&ZGA"=length(Y_N_Y_Y),
      "Sperm&Pre-ZGA&ZGA"=length(N_Y_Y_Y), "Spermatid&Sperm&Pre-ZGA&ZGA"=length(Y_Y_Y_Y))),
     quantities = TRUE,  fills=euler_cols[c("Y_N_N_N", "N_Y_N_N", "N_N_Y_N", "N_N_N_Y", "Y_Y_N_N", "Y_N_Y_N", "Y_N_N_Y", "N_Y_Y_N", "N_Y_N_Y", "N_N_Y_Y", "Y_Y_Y_N", "Y_Y_N_Y", "Y_N_Y_Y", "N_Y_Y_Y", "Y_Y_Y_Y")])
```



## Alluvial plots
```{r message=FALSE, warning=FALSE}
library(plyr)
library(ggalluvial)
library(dplyr)
library(ggpubr)

plot_alluvial <- function(remove_NNNN, remove_YYYY){
  get_row <- function(chip_dyn){
    levels = unlist(strsplit(names(chip_dyn), split = "_"))
    return(c(levels, length(chip_dyn[[1]]), names(chip_dyn)))
  }
  plot_df = data.frame()
  for (i in 1:length(chip_dyns_complete)){
    row = get_row(chip_dyns_complete[i])
    plot_df = rbind(plot_df, row)
  }
  #if(clustered_chip_groups){
  #  plot_df <- plot_df[plot_df[,ncol(plot_df)] %in% unlist(chip_clustering),]
  #}
  
  colnames(plot_df) <- c(stages, "Freq", "Dynamic")
  plot_df <- plot_df %>% mutate_at("Freq", as.numeric)
  
  if(remove_NNNN){plot_df <- plot_df[!plot_df$Dynamic %in% c("N_N_N_N"),]}
  if(remove_YYYY){plot_df <- plot_df[!plot_df$Dynamic %in% c("Y_Y_Y_Y"),]}
  
  for(stage in stages){
    plot_df[,stage] <- factor(plot_df[,stage], levels=c("Y", "N"))
  }
  
  ggplot(plot_df,
         aes(y = Freq, axis1 = Spermatid, axis2 = Sperm, axis3= `Pre-ZGA`, axis4 = ZGA, fill=Dynamic)) +
    geom_alluvium(aes(fill = Dynamic), width = 1/12) + theme_pubr() +
    geom_stratum(width = 1/12, fill = "grey", color = "black", alpha = .75) +
    geom_label(stat = "stratum", aes(label = after_stat(stratum))) +
    scale_x_discrete(limits = c("Spermatid", "Sperm", "Pre-ZGA", "ZGA"), expand = c(.05, .05)) +
    scale_fill_manual(values=euler_cols)
}

plot_alluvial(remove_NNNN = FALSE, remove_YYYY = FALSE)
plot_alluvial(remove_NNNN = TRUE, remove_YYYY = FALSE)
plot_alluvial(remove_NNNN = TRUE, remove_YYYY = TRUE)

```


###GO analysis on each gene group
```{r fig.height=12, fig.width=8, message=FALSE, warning=FALSE}
library(clusterProfiler)
library(org.Xl.eg.db)
library(simplifyEnrichment)
library(gridExtra)
library(grid)
Xl_ENTREZ <- read.delim("~/Documents/PhD/01_Projects/NT/Meghana_H3K4me3/NGS_data_sorted/Genome_Xl10.1/GenePageLaevisEntrezGeneUnigeneMapping.txt", header = FALSE)

go_enrichment <- function(data) {
  entrez <- Xl_ENTREZ[Xl_ENTREZ$V2 %in% data, ] 
  colnames(entrez) <- c("Xenbase ID", "Gene symbol", "Entrez ID", "Xl ID unknown")
  GO <- enrichGO(entrez$`Entrez ID`, OrgDb = org.Xl.eg.db, ont = "BP", readable = TRUE)
  return(GO)
}
plot_go <- function(enrichGO, name){
  dp <- dotplot(enrichGO)
  cn <- cnetplot(enrichGO)
  grid.arrange(dp, cn, top=name, nrow=2)
}

for (i in 1:length(chip_dyns)){
  chip_GO <- go_enrichment(chip_dyns[[i]])
  if(sum(chip_GO@result$p.adjust < chip_GO@pvalueCutoff)){
    plot_go(chip_GO, names(chip_dyns)[i])
  }
}
```


```{r message=FALSE, warning=FALSE}
for (i in 1:length(chip_dyns)){
  enrichGO <- go_enrichment(chip_dyns[[i]])
  hits <- enrichGO@result$ID[enrichGO@result$p.adjust<0.05]
  if(length(hits)>1){simplifyGO(GO_similarity(hits, db = 'org.Xl.eg.db'), column_title = names(chip_dyns[i]))}
}
```
```{r fig.height=6, fig.width=10, message=FALSE, warning=FALSE}
p_adj = 0.01
go_list <- lapply(chip_dyns, go_enrichment)
go_list <- go_list[unlist(lapply(go_list, function(enrichGO){sum(enrichGO@result$p.adjust<p_adj) > 0}))]
go_list <- lapply(go_list, function(x) x$ID[x$p.adjust < p_adj])
simplifyGOFromMultipleLists(go_list, padj_cutoff=p_adj, db = 'org.Xl.eg.db', ont = "BP")
```

#Differences in Maintenance at each transition
```{r fig.height=5, fig.width=10}
transition_diff <- function(transition, type){
  prev_stage <- transition[1]
  next_stage <- transition[2]
  genes_prev <- chip_dfs[[prev_stage]]$peak
  genes_maintain <- chip_dfs[[next_stage]]$peak
  plot_df <- data.frame(allgenes$gene_id[genes_prev], factor(genes_maintain[genes_prev], levels=c("FALSE","TRUE"),labels=c("Not maintained", "Maintained")),
                                                                                    chip_dfs[[prev_stage]][genes_prev, type])
  colnames(plot_df) <- c("Gene", "H3K4me3", type)
  violin_plot <- ggviolin(plot_df, x = "H3K4me3", y = paste(type), fill = "H3K4me3",
         add = "boxplot", add.params = list(fill = "white")) + stat_compare_means(comparisons = list( c("Maintained", "Not maintained")),method = "wilcox.test", label = "p.signif") + ylab(paste(type, prev_stage))
  ecdf_plot <- ggecdf(plot_df, x = paste(type), color = "H3K4me3") + xlab(paste(type, prev_stage))
  grid.arrange(violin_plot, ecdf_plot, top=paste("Maintenance from", prev_stage, "to", next_stage), ncol=2)
}

transitions <- list(c("Spermatid", "Sperm"), c("Sperm", "Pre-ZGA"), c("Pre-ZGA", "ZGA"), c("Spermatid", "ZGA"))
res <- lapply(transitions, transition_diff, type="peak.width")
res <- lapply(transitions, transition_diff, type="promoter.enrich")
res <- lapply(transitions, transition_diff, type="promoter.mean")
res <- lapply(transitions, transition_diff, type="promoter.max")
```

```{r message=FALSE, warning=FALSE}
library(PerformanceAnalytics)
corr_plot <- function(stage){
  plot_df <- chip_dfs[[stage]]
  plot_df <- plot_df[plot_df$peak,c("peak.width", "promoter.enrich", "promoter.max", "promoter.mean")]
  chart.Correlation(plot_df, histogram = TRUE, method = "spearman")
  mtext(paste(stage), side=3, line=3)
}

res <- lapply(stages, corr_plot)

```

