---
title: "Meghana H3K4me3 Maintenance - 00 Other"
output: html_notebook
---

#Overall peak analysis
```{r fig.height=5, fig.width=10}
library(ggpubr)
require(reshape2)
library(ggplot2)
library(gridExtra)

mask_peak <- function(df){
  df$promoter.enrich[!df$peak] <- NA
  df$promoter.max[!df$peak] <- NA
  df$promoter.mean[!df$peak] <- NA
  return(df)
}
preproc_df <- function(type){
  dfs <- chip_dfs
  #dfs <- lapply(dfs, mask_peak)
  
  plot_df <- do.call(cbind, dfs)
  plot_df <- plot_df[, grep(type, colnames(plot_df))]
  plot_df$genes <- allgenes$gene_id
  plot_df <- melt(plot_df)
  colnames(plot_df) <- c("Gene","Stage", paste(type)) 
  plot_df[is.na(plot_df[,paste(type)]),paste(type)] <- 0
  #plot_df <- plot_df[!is.na(plot_df[,type]),]
  plot_df$Stage <- factor(plot_df$Stage, levels=levels(plot_df$Stage), labels=substr(levels(plot_df$Stage), 1, nchar(levels(plot_df$Stage))-nchar(type)-1))
  return(plot_df)
}

plot_distribution <- function(type){
  plot_df <- preproc_df(type)
  density_plot <- ggdensity(data=plot_df, x=paste(type), fill = "Stage", add_density = TRUE) #+ facet_wrap(~Stage)
  ecdf_plot <- ggecdf(data=plot_df, x=paste(type), color = "Stage") #+guides(colour = "none")
  grid.arrange(density_plot, ecdf_plot, ncol=2)
}

types = list("peak.width", "promoter.enrich", "promoter.mean", "promoter.max")
res <- lapply(types, plot_distribution)
```

## late night session misc
```{r}
df <- chip_dfs[["Sperm"]]
df$gene_length <- width(allgenes)
ggscatter(df, x="gene_length", y="peak.width") + xlim(0, 10000)
weird <- rownames(df[!is.na(df$peak.width),])[df$gene_length[!is.na(df$peak.width)]+5000 < df$peak.width[!is.na(df$peak.width)]]
res <- lapply(rna_dyns, function(dyn){intersect(weird, dyn)})
str(res)
# remove peaks that span multiple promoters?


label_dyn <- function(gene, dyns){for(i in 1:length(dyns)){if(any(gene %in% dyns[[i]])){return(names(dyns)[i])}}; return(NA)}

plot_df <- chip_dfs[["Sperm"]]
plot_df$dyn <- sapply(rownames(plot_df), label_dyn, dyns = rna_dyns)
#plot_df <- plot_df[plot_df$peak,c("peak.width", "promoter.enrich", "promoter.max", "promoter.mean")]
ggscatter(plot_df, x="peak.width", "promoter.enrich", color="dyn")+facet_wrap(~dyn)

View(plot_df[plot_df$dyn == "ZS",])

res <- plot_df[plot_df$peak,]
wide_zs_sperm <- rownames(res)[res$dyn == "ZS" & (res$peak.width>3000)]

lapply(chip_dyns, function(dyn) intersect(wide_zs_sperm, dyn))

gs_gained <- intersect(chip_dyns$Gained, rna_dyns$GS)
str(chip_dyns)

enrichGO <- go_enrichment(gs_gained)
hits <- enrichGO@result$ID[enrichGO@result$p.adjust<0.05]
if(length(hits)>1){simplifyGO(GO_similarity(hits, db = 'org.Xl.eg.db'))}
```


```{r}
###Venn diagram with all gene groups
library(VennDiagram)
grid.newpage()
venn <- venn.diagram(
        x = list(egg.detected, spermatid.detected, zga_nascent.detected), filename=NULL, output=TRUE,
        category.names = c("Detected in Egg" , "Detected in\nSpermatid" , "Detected at ZGA (nascent)"))

grid.draw(venn)

grid.newpage()
venn <- venn.diagram(
        x = list(unique(chen[zga_nascent.6hpf, "name"]), unique(chen[zga_nascent.7hpf, "name"]), unique(chen[zga_nascent.8hpf, "name"]), unique(chen[zga_nascent.9hpf, "name"])), filename=NULL, output=TRUE,
        category.names = c("Detected at 6hpf" , "Detected at 7hpf", "Detected at 8hpf", "Detected at 9hpf"))
grid.draw(venn)
```


```{r}
#Binarization
library(plotGMM)
library(mixtools)
set.seed(12)
binarize_bimodal <- function(data, title) {
  data <- data[,1]
  em_data <-  normalmixEM(data, k = 2)
  cut_off <- plot_cut_point(em_data, plot = FALSE)
  plot(plot_cut_point(em_data, plot = TRUE, color = "amerika"))
  binarized = data>=cut_off[1]
  return(binarized)
}

H3K4me3_spermatid.binarized = binarize_bimodal(H3K4me3_spermatid, "Spermatid")
H3K4me3_sperm.binarized = binarize_bimodal(H3K4me3_sperm, "Sperm")
H3K4me3_prezga.binarized = binarize_bimodal(H3K4me3_prezga, "256c")
H3K4me3_zga.binarized = binarize_bimodal(H3K4me3_zga, "St10.5")
```

##Load dataset: Sperm H3K4me3 Oikawa (alternative - don't run)
```{r eval=FALSE, warning=FALSE, include=FALSE}
setwd("~/Documents/PhD/01_Projects/NT/Meghana_H3K4me3/NGS_data_sorted/1_Sperm_H3K4me3_Oikawa_Xl10.1")

#Load data
#H3K4me3_sperm.cov1 <- readGranges("GSM3587294_ranges.rds")
H3K4me3_sperm.cov2 <- readGranges("GSM3587295_ranges.rds")
H3K4me3_sperm.cov3 <- readGranges("GSM3587296_ranges.rds")
H3K4me3_sperm.cov <- c(H3K4me3_sperm.cov2, H3K4me3_sperm.cov3)

#Merged data
H3K4me3_sperm <- enrichment(H3K4me3_sperm.cov, "Sperm Merged Reps")
H3K4me3_sperm <- enriched_score(H3K4me3_sperm_raw)

#Individual replicates (optional)
#H3K4me3_sperm.rep1 <- enrichment(H3K4me3_sperm.cov1, "Sperm Rep1")
#H3K4me3_sperm.rep2 <- enrichment(H3K4me3_sperm.cov2, "Sperm Rep2")
#H3K4me3_sperm.rep3 <- enrichment(H3K4me3_sperm.cov3, "Sperm Rep3")

rm(H3K4me3_sperm.cov2, H3K4me3_sperm.cov3, H3K4me3_sperm.cov)
print("Dataset: Sperm H3K4me3 Oikawa loaded")
```

## Load peak calling data (narrow)
```{r message=FALSE, warning=FALSE}
library(rtracklayer)
library(ggpubr)
#Load bed files for spermatid, sperm, pre-ZGA, post-ZGA
setwd("~/Documents/PhD/01_Projects/NT/Meghana_H3K4me3/NGS_data_sorted/8_Sperm-spermatid_H3K4me3_Teperek_Xl10.1")
D0_bed1 <- import("GSM1944497.bed", format = "bed")
D0_bed2 <- import("GSM1944498.bed", format = "bed")
D0_bed3 <- import("GSM1944499.bed", format = "bed")
D0_spdH3K4me3_bed <- c(D0_bed1, D0_bed2, D0_bed3)

setwd("~/Documents/PhD/01_Projects/NT/Meghana_H3K4me3/NGS_data_sorted/1_Sperm_H3K4me3_Oikawa_Xl10.1")
D1_bed2 <- import("GSM3587295.bed", format = "bed")
D1_bed3 <- import("GSM3587296.bed", format = "bed")
D1_spH3K4me3_bed <- c(D1_bed2, D1_bed3)

setwd("~/Documents/PhD/01_Projects/NT/Meghana_H3K4me3/NGS_data_sorted/3_256c_H3K4me3_Eva-Oikawa_Xl10.1")
D3_bed1 <- import("H3K4me3_IP1_GSM3671368.bed", format = "bed")
D3_bed2 <- import("H3K4me3_IP2_GSM3671369.bed", format = "bed")
D3_S7H3K4me3_bed <- c(D3_bed1, D3_bed2)

setwd("~/Documents/PhD/01_Projects/NT/Meghana_H3K4me3/NGS_data_sorted/6_St10.5_H3K4me3_Session_Xl10.1/GSE76059")
D6_bed1 <- import("GSM1973491.bed", format = "bed")
D6_bed2 <- import("GSM1973492.bed", format = "bed")
D6_S10H3K4me3_bed <- c(D6_bed1, D6_bed2)

rm(D0_bed1, D0_bed2, D0_bed3, D1_bed2, D1_bed3, D3_bed1, D3_bed2, D6_bed1, D6_bed2)

promoters_1kb <- promoters(allgenes, upstream = 1000, downstream = 1000)
h3k4stages <- list(D0_spdH3K4me3_bed, D1_spH3K4me3_bed, D3_S7H3K4me3_bed, D6_S10H3K4me3_bed)
h3k4prostages <- lapply(h3k4stages, function(x){promoters_1kb$gene_id[findOverlaps(promoters_1kb, x, select = "first") != "NA"]})
names(h3k4prostages) <- c("Spermatid", "Sperm", "Pre-ZGA", "ZGA")

H3K4me3_spermatid.binarized = !is.na(h3k4prostages[["Spermatid"]])
H3K4me3_sperm.binarized = !is.na(h3k4prostages[["Sperm"]])
H3K4me3_prezga.binarized = !is.na(h3k4prostages[["Pre-ZGA"]])
H3K4me3_zga.binarized = !is.na(h3k4prostages[["ZGA"]])
```

```{r}
#Heatmap
hm_data <- cbind(H3K4me3_spermatid, H3K4me3_sperm, H3K4me3_prezga, H3K4me3_zga, NA)
colnames(hm_data) <- c("Spermatid", "Sperm", "256c", "St10.5", "Dynamics")
hm_data[L_H_H_H, "Dynamics"] <- "0-1-1-1"
hm_data[L_H_H_L, "Dynamics"] <- "0-1-1-0"
hm_data[L_H_L_H, "Dynamics"] <- "0-1-0-1"
hm_data[L_H_L_L, "Dynamics"] <- "0-1-0-0"
hm_data[L_L_H_H, "Dynamics"] <- "0-0-1-1"
hm_data[L_L_H_L, "Dynamics"] <- "0-0-1-0"
hm_data[L_L_L_H, "Dynamics"] <- "0-0-0-1"
hm_data[L_L_L_L, "Dynamics"] <- "0-0-0-0"

hm_data[H_H_H_H, "Dynamics"] <- "1-1-1-1"
hm_data[H_H_H_L, "Dynamics"] <- "1-1-1-0"
hm_data[H_H_L_H, "Dynamics"] <- "1-1-0-1"
hm_data[H_H_L_L, "Dynamics"] <- "1-1-0-0"
hm_data[H_L_H_H, "Dynamics"] <- "1-0-1-1"
hm_data[H_L_H_L, "Dynamics"] <- "1-0-1-0"
hm_data[H_L_L_H, "Dynamics"] <- "1-0-0-1"
hm_data[H_L_L_L, "Dynamics"] <- "1-0-0-0"
hm_data$Dynamics <- as.factor(hm_data$Dynamics)


library(ComplexHeatmap)
library(circlize)
col_fun = colorRamp2(c(0,100), c("blue", "red"))
#Heatmap(hm_data[1:4], name = "H3K4me3 enrichment", column_title = "H3K4me3 dynamics groups", cluster_rows = FALSE, 
#        show_row_names = FALSE, row_split = hm_data$Dynamics, row_title_rot = 0, col = col_fun)

Heatmap(hm_data[1:4], name = "H3K4me3 enrichment", column_title = "H3K4me3 dynamics groups", cluster_rows = TRUE, 
        show_row_names = FALSE, row_title_rot = 0, col = col_fun)
```

